//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpentryShop.CarpentryShopDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryCarpenter
    {
        public int idInventory { get; set; }
        public int idCarpenter { get; set; }
        public Nullable<int> idInventoryTool { get; set; }
        public Nullable<int> idInventoryMetalDetails { get; set; }
        public Nullable<int> idInventoryMaterials { get; set; }
        public Nullable<int> idInventoryWoodDetails { get; set; }
    
        public virtual Carpenter Carpenter { get; set; }
        public virtual InventoryMetalDetails InventoryMetalDetails { get; set; }
        public virtual InventoryMaterials InventoryMaterials { get; set; }
        public virtual InventoryTools InventoryTools { get; set; }
        public virtual InventoryWoodDetails InventoryWoodDetails { get; set; }
    }
}
