//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpentryShop.CarpentryShopDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int idProduct { get; set; }
        public string NameProduct { get; set; }
        public byte[] ImageProduct { get; set; }
        public Nullable<int> idProductReceipt { get; set; }
    
        public virtual ProductReceipts ProductReceipts { get; set; }
    }
}
