//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarpentryShop.CarpentryShopDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductReceiptDetails
    {
        public int idProductReceiptDetail { get; set; }
        public Nullable<int> idWoodDetail { get; set; }
        public Nullable<int> idMetalDetail { get; set; }
        public int idProductReceipt { get; set; }
    
        public virtual MetalDetails MetalDetails { get; set; }
        public virtual ProductReceipts ProductReceipts { get; set; }
        public virtual WoodDetails WoodDetails { get; set; }
    }
}
